#server:
#  port: 8081
##  servlet:
##    context-path: /user-service
#spring:
#  application:
#    name: user-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/hotel_management
#    username: root
#    password: Saurabh*789
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update # alternatives: none, validate, update, create, create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  config:
#    import: configserver : http://localhost:8084
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#
#otel:
#  exporter:
#    otlp:
#      endpoint: http://localhost:4318
#  resource:
#    attributes:
#      service:
#        name: user-service
#  traces:
#    sampler:
#      ratio: 1.0
#
##management:
##  tracing:
##    sampling:
##      probability: 1.0  # capture all traces
##    otlp:
##      endpoint: http://localhost:4318/v1/traces
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#    propagation:
#      type: w3c
#
#  otlp:
#    tracing:
#      endpoint: http://localhost:4318/v1/traces  # or your Jaeger collector URL
#
#
#tracing:
#  url: http://localhost:4318/v1/traces
#
#
#
#
#


spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: user-service

management:
  endpoints:
    web:
      exposure:
        include: resilience4j.circuitbreakers, health


resilience4j:
  circuitbreaker:
    instances:
      ratingHotelCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5                  # Check last 5 calls
        minimumNumberOfCalls: 5                # Minimum 5 calls before calculating failure rate
        failureRateThreshold: 50               # Open the circuit if 50% calls fail
        waitDurationInOpenState: 10s           # Keep the circuit open for 10 seconds
        permittedNumberOfCallsInHalfOpenState: 3  # In half-open state, allow 3 trial calls
        automaticTransitionFromOpenToHalfOpenEnabled: true # Auto move to half-open after wait
  timelimiter:
    instances:
      ratingHotelCircuitBreaker:
        timeoutDuration: 3s

